# Generated by Django 4.2.3 on 2023-07-13 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DateNow',
        ),
    ]
